
jobs:
  include:
    - stage: Deploy
      script: skip
      before_install: []
      install: skip
      if: tag =~ /^v\d\.\d\.\d$/
      deploy:
        - provider: 'rubygems'
          on:
            repo: lwoggardner/ffi-libfuse
            tags: true
          api_key:
            secure:
    - stage: 'PreRelease'
      if: branch =~ ^rc
      script: skip
      before_install: []
      install: skip
      deploy:
        - provider: 'rubygems'
          on:
            repo: lwoggardner/ffi-libfuse
            all_branches: true
            condition: '$TRAVIS_BRANCH =~ ^rc'
          api_key:
            secure:
language: ruby
dist: focal
rvm:
  - "2.6"
  - "2.7"

before_install:
  - sudo apt-get update -y
  - sudo apt-get install -qq pkg-config fuse
  - sudo modprobe fuse
  - sudo chmod 666 /dev/fuse
  - sudo chown root:$USER /etc/fuse.conf
  - yes | gem update --system -N --force
  - gem install bundler

script:
  - bundle exec rake

cache:
  bundler: true
