name: Build

on:
  push:
    # TODO: rc* branches from this workflow (they will use the deploy workflow otherwise reserved for tag
    branches:
      - "**"
jobs:
  build:
    strategy:
      matrix:
        ruby-version: ['2.7', '3.0', '3.1', '3.2']
        os: ['ubuntu-latest'] # mac-os when/if Macfuse can be deployed on CI images
        fuse-pkg: ['fuse2','fuse3']
        include:
          - os: 'ubuntu-latest'
            fuse_pkg: 'fuse2'
            libfuse: 'libfuse.so.2'
            pre_install: 'linux'
          - os: 'ubuntu-latest'
            fuse_pkg: 'fuse3'
            libfuse: 'libfuse3.so.3'
            pre_install: 'linux'

    runs-on: ${{ matrix.os }}
    env:  # Used in gemspec to determine version
      # TODO: These are available as GITHUB_ variables but lets get it working first
      TRAVIS_BUILD_NUMBER: ${{ github.run_number }}
      TRAVIS_BRANCH_NAME: ${{ github.ref_name }}
      TRAVIS_BUILD_STAGE_NAME: ${{ github.job }}
    steps:
      - uses: actions/checkout@v3
      - name: Preinstall
        env:
          FUSE_PKG: ${{ matrix.fuse_pkg }}
        run: .github/scripts/pre_install_${{matrix.pre_install}}.sh
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Update system gems
        run: gem update --system

      - name: Run tests
        env:
          LIB_FUSE: ${{ matrix.libfuse }}
        run: bundle exec rake
  deploy:
    needs: build
    runs_on: 'ubuntu_latest'
    steps:
      - uses: actions/checkout@v3
      - name: Preinstall
        env:
          FUSE_PKG: ${{ matrix.fuse_pkg }}
        run: .github/scripts/pre_install_${{matrix.pre_install}}.sh
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true