name: Build

on:
  push:
    # TODO: rc* branches from this workflow (they will use the deploy workflow otherwise reserved for tag
    branches:
      - "**"
jobs:
  build:
    strategy:
      matrix:
        ruby-version: ['2.7', '3.0', '3.1', '3.2']
        os: ['ubuntu-latest'] # mac-os when/if Macfuse can be deployed on CI images
        fuse_pkg: ['fuse','fuse3']

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Preinstall
        env:
          FUSE_PKG: ${{ matrix.fuse_pkg }}
        run: .github/scripts/pre_install_${{runner.os}}.sh
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run tests
        env:
          TERM: color # Pretty spec output
        run: bundle exec rake