name: Publish

on:
  push:
    tag:
      - "v[0-9]+.[0-9]+.[0-9]+*"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - run: gem install gem-release
      - name: publish
        run: bundle exec rake publish