# Tag and Release
name: Release

on:
  workflow_dispatch:  # run for pre-existing tag or against a branch
  push: # If semver tag applied manually - probably not required
    tag:
      - "v[0-9]+.[0-9]+.[0-9]+*"   # semver tags
  workflow_call: # From release-please
    secrets:
      RUBYGEMS_API_KEY:
        required: true
jobs:
  # TODO: Confirm when we use @ref in workflow call GITHUB_REF_TYPE, GITHUB_REF_NAME use that ref
  #   ie so that checkout gets a tag rather than the original branch
  debug-github:
    runs-on: ubuntu-latest
    steps:
    - run: echo "${JSON}"
      env:
        JSON: ${{ toJSON(github) }}
  call-build:  # Ultra safety
    uses: ./.github/workflows/build.yaml
  release:
    needs: call-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Setup Credentials
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          git config user.name "${GITHUB_USER_NAME}"
          git config user.email "<>"
        env:
          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_API_KEY}}"
          GITHUB_USER_NAME: "GitHub Action ${{github.workflow}}"
      - name: Release
        run: bundle exec rake release
