# Tag and Release
name: Release

on:
  workflow-call:
  #tag:
  #  - "v[0-9]+.[0-9]+.[0-9]+"    # release tags
  #  - "v[0-9]+.[0-9]+.[0-9]+.*"  # pre-release tags
jobs:
  call-build:  # build all platforms
    uses: ./.github/workflows/build.yaml
  release:
    needs: call-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - run: gem install gem-release
      - name: Setup Credentials
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n:github: Bearer ${GITHUB_TOKEN}\n" > $HOME/.gem/credentials
        env:
          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_API_KEY}}"
          GITHUB_TOKEN: ${{ github.token }}
      - name: Tag and Release
        run: bundle exec rake release[--color]

